# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "validation_scopes"
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Gabe da Silveira"]
  s.date = "2012-04-15"
  s.description = "Define additional sets of validations beyond the standard \"errors\" that is tied to the ActiveRecord life-cycle.  These additional sets can be defined with all the standard ActiveRecord::Validation macros, and the resulting collection is a standard ActiveRecord::Errors object."
  s.email = "gabe@websaviour.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "CHANGELOG",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/validation_scopes.rb",
    "test/db/schema.rb",
    "test/fixtures/books.yml",
    "test/fixtures/users.yml",
    "test/helper.rb",
    "test/models/book.rb",
    "test/models/user.rb",
    "test/test_validation_scopes.rb",
    "validation_scopes.gemspec"
  ]
  s.homepage = "http://github.com/dasil003/validation_scopes"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.22"
  s.summary = "Create sets of validations independent of the life-cycle of an ActiveRecord object"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

